# Generated by Django 5.0.1 on 2024-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('bname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
