# Generated by Django 5.0.1 on 2024-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=50)),
                ('b_id', models.CharField(max_length=50)),
                ('i_date', models.DateField()),
                ('r_date', models.DateField()),
                ('fine', models.IntegerField()),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AlterField(
            model_name='books',
            name='bookid',
            field=models.CharField(max_length=50),
        ),
    ]
