# Generated by Django 5.0.1 on 2024-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managsys', '0002_issue_student_alter_books_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='r_date',
            field=models.DateField(default=None),
        ),
    ]
