# Generated by Django 5.0.1 on 2024-02-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managsys', '0004_alter_issue_r_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
