# Generated by Django 5.0.1 on 2024-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managsys', '0005_alter_issue_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
